# Generated by Django 5.1.5 on 2025-02-13 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0006_alter_c_aplicacion_fhalta_alter_c_modulo_fhalta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_aplicacion',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 2, 13, 17, 5, 39, 70316, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='c_modulo',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 2, 13, 17, 5, 39, 70453, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='t_etapa',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 2, 13, 17, 5, 39, 69528, tzinfo=datetime.timezone.utc), help_text='Fecha y hora del alta', verbose_name='Fecha y hora del alta'),
        ),
        migrations.AlterField(
            model_name='t_requisito',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 2, 13, 17, 5, 39, 68907, tzinfo=datetime.timezone.utc), help_text='Fecha y hora del alta', verbose_name='Fecha y hora del alta'),
        ),
        migrations.AlterField(
            model_name='t_tramite',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 2, 13, 17, 5, 39, 69227, tzinfo=datetime.timezone.utc), help_text='Fecha y hora del alta', verbose_name='Fecha y hora del alta'),
        ),
    ]
