# Generated by Django 5.1.5 on 2025-03-22 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0007_alter_c_aplicacion_fhalta_alter_c_modulo_fhalta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='EstadoFinal',
            field=models.JSONField(db_column='ESTADOFINAL', null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='EstadoInicial',
            field=models.JSONField(db_column='ESTADOINICIAL', null=True),
        ),
        migrations.AlterField(
            model_name='c_aplicacion',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 3, 22, 19, 37, 16, 402152, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='c_modulo',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 3, 22, 19, 37, 16, 402300, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='t_etapa',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 3, 22, 19, 37, 16, 401315, tzinfo=datetime.timezone.utc), help_text='Fecha y hora del alta', verbose_name='Fecha y hora del alta'),
        ),
        migrations.AlterField(
            model_name='t_requisito',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 3, 22, 19, 37, 16, 400655, tzinfo=datetime.timezone.utc), help_text='Fecha y hora del alta', verbose_name='Fecha y hora del alta'),
        ),
        migrations.AlterField(
            model_name='t_tramite',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 3, 22, 19, 37, 16, 400996, tzinfo=datetime.timezone.utc), help_text='Fecha y hora del alta', verbose_name='Fecha y hora del alta'),
        ),
    ]
