# Generated by Django 5.1.5 on 2025-05-04 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0010_alter_c_aplicacion_fhalta_alter_c_modulo_fhalta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_aplicacion',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 5, 4, 2, 31, 10, 654413, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='c_modulo',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 5, 4, 2, 31, 10, 654562, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='t_etapa',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 5, 4, 2, 31, 10, 653586, tzinfo=datetime.timezone.utc), help_text='Fecha y hora del alta', verbose_name='Fecha y hora del alta'),
        ),
        migrations.AlterField(
            model_name='t_requisito',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 5, 4, 2, 31, 10, 652933, tzinfo=datetime.timezone.utc), help_text='Fecha y hora del alta', verbose_name='Fecha y hora del alta'),
        ),
        migrations.AlterField(
            model_name='t_tramite',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 5, 4, 2, 31, 10, 653271, tzinfo=datetime.timezone.utc), help_text='Fecha y hora del alta', verbose_name='Fecha y hora del alta'),
        ),
    ]
