# Generated by Django 5.1.5 on 2025-05-04 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0012_alter_c_aplicacion_fhalta_alter_c_modulo_fhalta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_aplicacion',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 5, 4, 2, 55, 43, 315254, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='c_modulo',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 5, 4, 2, 55, 43, 315391, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='t_etapa',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 5, 4, 2, 55, 43, 314464, tzinfo=datetime.timezone.utc), help_text='Fecha y hora del alta', verbose_name='Fecha y hora del alta'),
        ),
        migrations.AlterField(
            model_name='t_requisito',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 5, 4, 2, 55, 43, 313840, tzinfo=datetime.timezone.utc), help_text='Fecha y hora del alta', verbose_name='Fecha y hora del alta'),
        ),
        migrations.AlterField(
            model_name='t_tramite',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 5, 4, 2, 55, 43, 314158, tzinfo=datetime.timezone.utc), help_text='Fecha y hora del alta', verbose_name='Fecha y hora del alta'),
        ),
    ]
