# Generated by Django 5.1.5 on 2025-02-08 01:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='c_area',
            fields=[
                ('IdArea', models.BigAutoField(db_column='IDAREA', db_index=True, primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(db_column='NOMBRE', max_length=50, unique=True, verbose_name='Área')),
                ('Descripcion', models.TextField(db_column='DESCRIPCION', null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Áreas de la organización',
                'ordering': ('Nombre',),
            },
        ),
        migrations.CreateModel(
            name='c_dependencia',
            fields=[
                ('IdDependencia', models.BigAutoField(db_column='IDDEPENDENCIA', db_index=True, primary_key=True, serialize=False)),
                ('NivelGobierno', models.PositiveSmallIntegerField(choices=[(0, 'Sin determinar'), (1, 'Municipal'), (2, 'Estatal o provincial'), (3, 'Federal o nacional'), (4, 'Gobierno extranjero')], db_column='NIVELGOBIERNO', db_default=0, verbose_name='Nivel de Goberno')),
                ('Poder', models.IntegerField(choices=[(0, 'Sin determinar'), (1, 'Ejecutivo'), (2, 'Legislativo'), (3, 'Judicial'), (4, 'Electoral'), (5, 'Otro')], db_column='PODER', db_default=0, verbose_name='¿A cuál poder pertenece?')),
                ('Nombre', models.CharField(db_column='NOMBRE', max_length=100, verbose_name='Dependencia')),
                ('NombreAnterior', models.CharField(db_column='NOMBREANTERIOR', max_length=100, null=True, verbose_name='Nombre anterior (si lo tuviese)')),
                ('FHAlta', models.DateTimeField(db_column='FHALTA', verbose_name='Fecha del alta')),
                ('FHModificacion', models.DateTimeField(db_column='FMODIF', verbose_name='Fecha de la última modificación')),
                ('Vialidad', models.CharField(db_column='NOMVIALIDAD', db_index=True, max_length=100, null=True)),
                ('TipoVialidad', models.PositiveSmallIntegerField(choices=[(0, 'Calle'), (1, 'Avenida'), (2, 'Periférico'), (3, 'Cerrada'), (4, 'Calzada'), (5, 'Eje vial'), (6, 'Privada'), (7, 'Circuito'), (8, 'Viaducto'), (9, 'Pasaje'), (10, 'Peatonal'), (11, 'Continuación'), (12, 'Callejón'), (13, 'Corredor'), (14, 'Prolongación'), (15, 'Andador'), (16, 'Carretera'), (17, 'Boulevard'), (18, 'Ampliación'), (19, 'Circunvalación'), (20, 'Glorieta'), (21, 'Carretera'), (22, 'Retorno'), (23, 'Enlace'), (24, 'Vereda'), (25, 'Diagonal'), (26, 'Retorno U'), (27, 'Rampa de frenado'), (28, 'Otro')], db_column='TIPOVIALIDAD', db_default=0)),
                ('NumeroExterior', models.CharField(db_column='NUMEXTERIOR', db_index=True, default='', help_text='Número exterior, manzana-lote, kilómetro, etc.', max_length=30, null=True, verbose_name='Número exterior')),
                ('NumeroInterior', models.CharField(db_column='NUMINTERIOR', help_text='Número interior, casa, departamento, etc.', max_length=30, null=True, verbose_name='Número interior')),
                ('ClaveGeogAsentamiento', models.ForeignKey(db_column='CLAVEASENTAMIENTO', help_text='Clase de asentamiento humano: Colonia, barrio, pueblo, etc.', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.c_asentamiento_humano', verbose_name='Asentamiento')),
                ('ClaveGeogLocalidad', models.ForeignKey(db_column='CVEGEOLOCALIDAD', help_text='Clave de localidad', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.c_localidad', verbose_name='Localidad')),
            ],
            options={
                'verbose_name_plural': 'Catálogo de dependencias',
                'ordering': ('Nombre', 'NombreAnterior', 'Poder', 'NivelGobierno'),
            },
        ),
        migrations.CreateModel(
            name='c_oficina',
            fields=[
                ('IdOficina', models.BigAutoField(db_column='IDOFICINA', db_index=True, primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(db_column='NOMBRE', max_length=50, unique=True, verbose_name='Oficina')),
                ('Descripcion', models.TextField(db_column='DESCRIPCION', verbose_name='Descripción')),
                ('Receptora', models.BooleanField(db_column='RECEPTORA', db_default=False, verbose_name='¿Es receptora de solicitudes de trámites')),
                ('Virtual', models.BooleanField(db_column='VIRTUAL', db_default=False, verbose_name='¿Es una oficina virtual?')),
                ('Registro', models.BooleanField(db_column='REGISTRO', db_default=False, verbose_name='¿Inscriben actos?')),
                ('ConAcervo', models.BooleanField(db_column='CONACERVO', db_default=False, verbose_name='¿Cuenta con un acervo histórico?')),
                ('Activo', models.BooleanField(db_column='ACTIVO', db_default=False, verbose_name='¿Es una oficina activa?')),
                ('Vialidad', models.CharField(db_column='NOMVIALIDAD', db_index=True, max_length=100, null=True)),
                ('TipoVialidad', models.PositiveSmallIntegerField(choices=[(0, 'Calle'), (1, 'Avenida'), (2, 'Periférico'), (3, 'Cerrada'), (4, 'Calzada'), (5, 'Eje vial'), (6, 'Privada'), (7, 'Circuito'), (8, 'Viaducto'), (9, 'Pasaje'), (10, 'Peatonal'), (11, 'Continuación'), (12, 'Callejón'), (13, 'Corredor'), (14, 'Prolongación'), (15, 'Andador'), (16, 'Carretera'), (17, 'Boulevard'), (18, 'Ampliación'), (19, 'Circunvalación'), (20, 'Glorieta'), (21, 'Carretera'), (22, 'Retorno'), (23, 'Enlace'), (24, 'Vereda'), (25, 'Diagonal'), (26, 'Retorno U'), (27, 'Rampa de frenado'), (28, 'Otro')], db_column='TIPOVIALIDAD', db_default=0)),
                ('NumeroExterior', models.CharField(db_column='NUMEXTERIOR', db_default='', db_index=True, help_text='Número exterior, manzana-lote, kilómetro, etc.', max_length=30, null=True, verbose_name='Número exterior')),
                ('NumeroInterior', models.CharField(db_column='NUMINTERIOR', db_default='', help_text='Número interior, casa, departamento, etc.', max_length=30, null=True, verbose_name='Número interior')),
                ('ClaveGeogAsentamiento', models.ForeignKey(db_column='CLAVEASENTAMIENTO', help_text='Clase de asentamiento humano: Colonia, barrio, pueblo, etc.', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.c_asentamiento_humano', verbose_name='Asentamiento')),
            ],
            options={
                'verbose_name_plural': 'Oficinas de la institución',
                'ordering': ('Nombre', 'Descripcion'),
            },
        ),
        migrations.CreateModel(
            name='fedatario_y_funcionario',
            fields=[
                ('idFedatarioFuncionario', models.BigAutoField(db_column='IDFEDFUNC', db_index=True, primary_key=True, serialize=False, unique=True)),
                ('Activo', models.BooleanField(db_column='ACTIVO', db_default=False)),
                ('Nombre', models.CharField(db_column='NOMBRE', max_length=100)),
                ('PrimerApellido', models.CharField(db_column='APELLIDO1', max_length=100)),
                ('SegundoApellido', models.CharField(db_column='APELLIDO2', max_length=100)),
                ('Telefono', models.CharField(db_column='TELEFONO', max_length=15)),
                ('CorreoElectronico', models.EmailField(db_column='CORREOELECTRONICO', max_length=254)),
                ('NombreOficina', models.CharField(db_column='OFICINA', max_length=50)),
                ('Tipo', models.IntegerField(choices=[(0, 'Notario'), (1, 'Corredor Público'), (2, 'Juez'), (3, 'Funcionario municipal'), (4, 'Funcionario estatal'), (5, 'Funcionario federal'), (6, 'Funcionario extranjero')], db_column='TIPO', db_default=0)),
                ('Nombramiento', models.CharField(db_column='NOMBRAMIENTO', max_length=100)),
                ('FNombramiento', models.DateField(db_column='FNOMBRAMIENTO')),
                ('FHAlta', models.DateTimeField(db_column='FHALTA')),
                ('FHModificacion', models.DateTimeField(db_column='FHMODIF')),
                ('Vialidad', models.CharField(db_column='NOMVIALIDAD', db_index=True, max_length=100, null=True)),
                ('TipoVialidad', models.PositiveSmallIntegerField(choices=[(0, 'Calle'), (1, 'Avenida'), (2, 'Periférico'), (3, 'Cerrada'), (4, 'Calzada'), (5, 'Eje vial'), (6, 'Privada'), (7, 'Circuito'), (8, 'Viaducto'), (9, 'Pasaje'), (10, 'Peatonal'), (11, 'Continuación'), (12, 'Callejón'), (13, 'Corredor'), (14, 'Prolongación'), (15, 'Andador'), (16, 'Carretera'), (17, 'Boulevard'), (18, 'Ampliación'), (19, 'Circunvalación'), (20, 'Glorieta'), (21, 'Carretera'), (22, 'Retorno'), (23, 'Enlace'), (24, 'Vereda'), (25, 'Diagonal'), (26, 'Retorno U'), (27, 'Rampa de frenado'), (28, 'Otro')], db_column='TIPOVIALIDAD', db_default=0)),
                ('NumeroExterior', models.CharField(db_column='NUMEXTERIOR', db_default='', db_index=True, help_text='Número exterior, manzana-lote, kilómetro, etc.', max_length=30, null=True, verbose_name='Número exterior')),
                ('NumeroInterior', models.CharField(db_column='NUMINTERIOR', db_default='', help_text='Número interior, casa, departamento, etc.', max_length=30, null=True, verbose_name='Número interior')),
                ('ClaveGeogAsentamiento', models.ForeignKey(db_column='CLAVEASENTAMIENTO', help_text='Clase de asentamiento humano: Colonia, barrio, pueblo, etc.', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.c_asentamiento_humano', verbose_name='Asentamiento')),
                ('IdDependencia', models.ForeignKey(db_column='IDDEPENDENCIA', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminusr.c_dependencia')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('IdUsuario', models.BigIntegerField(db_column='IDUSUARIO', db_index=True, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='NOMBRE', db_index=True, max_length=100, verbose_name='Nombre')),
                ('PrimerApellido', models.CharField(db_column='APELLIDO1', db_index=True, max_length=100, verbose_name='Primer apellido')),
                ('SegundoApellido', models.CharField(db_column='APELLIDO2', db_index=True, max_length=100, verbose_name='Segundo apellido')),
                ('CURP', models.CharField(db_column='CURP', db_index=True, max_length=20, verbose_name='Clave única de registro de población')),
                ('RFC', models.CharField(db_column='RFC', max_length=15, null=True, verbose_name='Registro federal de contribuyentes')),
                ('PreguntaSeguridad', models.TextField(db_column='PREGUNTASEGURIDAD', verbose_name='Pregunta de seguridad')),
                ('RespuestaSeguridad', models.TextField(db_column='RESPUESTASEGURIDAD', verbose_name='Respuesta de seguridad')),
                ('Activo', models.BooleanField(db_column='ACTIVO', db_default=False, verbose_name='¿Es un usuairo activo?')),
                ('MotivoBaja', models.CharField(db_column='MOTIVOBAJA', max_length=200, null=True, verbose_name='Si no está activo: ¿Cuál es el motivo?')),
                ('Cargo', models.CharField(db_column='CARGO', max_length=100, null=True, verbose_name='Cargo que tiene')),
                ('AccesoFueraHorario', models.BooleanField(db_column='ACCESOFHORARIO', db_default=False, verbose_name='¿Accede fuera del horario laboral?')),
                ('FHAlta', models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 2, 8, 1, 35, 37, 58214, tzinfo=datetime.timezone.utc))),
                ('FHModificacion', models.DateTimeField(db_column='FHMODIF')),
                ('IdArea', models.ForeignKey(db_column='IDAREA', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminusr.c_area', verbose_name='Área al que está adscrito(a)')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema')),
            ],
            options={
                'verbose_name_plural': 'Usuarios intstitucionales',
                'ordering': ('PrimerApellido', 'SegundoApellido', 'Nombre', 'Cargo'),
            },
        ),
        migrations.CreateModel(
            name='usuario_externo',
            fields=[
                ('IdUsuarioExterno', models.BigIntegerField(db_column='IDUSUARIO', db_index=True, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='NOMBRE', db_index=True, max_length=100)),
                ('PrimerApellido', models.CharField(db_column='APELLIDO1', db_index=True, max_length=100)),
                ('SegundoApellido', models.CharField(db_column='APELLIDO2', db_index=True, max_length=100)),
                ('CURP', models.CharField(db_column='CURP', db_index=True, max_length=20)),
                ('RFC', models.CharField(db_column='RFC', max_length=15, null=True)),
                ('PreguntaSeguridad', models.TextField(db_column='PREGUNTASEGURIDAD')),
                ('RespuestaSeguridad', models.TextField(db_column='RESPUESTASEGURIDAD')),
                ('Activo', models.BooleanField(db_column='ACTIVO', db_default=False)),
                ('MotivoBaja', models.CharField(db_column='MOTIVOBAJA', max_length=200, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='usuario_oficial_externo',
            fields=[
                ('IdUsuarioOficialExterno', models.BigIntegerField(db_column='IDUSUARIO', db_index=True, primary_key=True, serialize=False)),
                ('PreguntaSeguridad', models.TextField(db_column='PREGUNTASEGURIDAD')),
                ('RespuestaSeguridad', models.TextField(db_column='RESPUESTASEGURIDAD')),
                ('Activo', models.BooleanField(db_column='ACTIVO', db_default=False)),
                ('MotivoBaja', models.CharField(db_column='MOTIVOBAJA', max_length=200, null=True)),
                ('DatosAdicionales', models.JSONField(db_column='DATOSADICIONALES')),
                ('FHAlta', models.DateTimeField(db_column='FHALTA')),
                ('FHModificacion', models.DateTimeField(db_column='FHMODIF')),
                ('IdFedatarioFuncionario', models.ForeignKey(db_column='IDFEDFUNC', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminusr.fedatario_y_funcionario')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
