# Generated by Django 5.1.5 on 2025-02-12 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminusr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 2, 12, 19, 0, 1, 926772, tzinfo=datetime.timezone.utc)),
        ),
    ]
