# Generated by Django 5.1.5 on 2025-02-12 19:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminusr', '0002_alter_usuario_fhalta'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_oficina',
            name='prefijo_oficina',
            field=models.CharField(db_column='PREFIJOOFICINA', db_default='00', help_text='Prefijo (2 posiciones) de la oficina registral', max_length=2, verbose_name='Prefijo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='idOficina',
            field=models.ForeignKey(db_column='IDOFICINA', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminusr.c_oficina', verbose_name='Oficina'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 2, 12, 19, 36, 32, 686744, tzinfo=datetime.timezone.utc)),
        ),
    ]
