# Generated by Django 5.1.5 on 2025-02-13 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminusr', '0003_c_oficina_prefijo_oficina_usuario_idoficina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 2, 13, 11, 48, 41, 381431, tzinfo=datetime.timezone.utc)),
        ),
    ]
