# Generated by Django 5.1.5 on 2025-02-13 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminusr', '0004_alter_usuario_fhalta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 2, 13, 11, 59, 25, 385459, tzinfo=datetime.timezone.utc)),
        ),
    ]
