# Generated by Django 5.1.5 on 2025-03-22 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminusr', '0007_alter_usuario_fhalta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 3, 22, 19, 37, 16, 386365, tzinfo=datetime.timezone.utc)),
        ),
    ]
