# Generated by Django 5.1.5 on 2025-05-04 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminusr', '0013_alter_usuario_fhalta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 5, 4, 3, 0, 57, 487264, tzinfo=datetime.timezone.utc)),
        ),
    ]
