# Generated by Django 5.1.5 on 2025-02-12 19:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autorizacion',
            options={'ordering': ('Cadena', 'FHAutorizacion'), 'verbose_name_plural': 'Autorizaciones'},
        ),
        migrations.RemoveField(
            model_name='acto_vario',
            name='DatosAdicionales',
        ),
        migrations.RemoveField(
            model_name='acto_vario',
            name='FHAlta',
        ),
        migrations.RemoveField(
            model_name='acto_vario',
            name='FHModificacion',
        ),
        migrations.RemoveField(
            model_name='aviso_preventivo',
            name='DatosAdicionales',
        ),
        migrations.RemoveField(
            model_name='aviso_preventivo',
            name='FHAlta',
        ),
        migrations.RemoveField(
            model_name='aviso_preventivo',
            name='FHModificacion',
        ),
        migrations.RemoveField(
            model_name='cesion',
            name='DatosAdicionales',
        ),
        migrations.RemoveField(
            model_name='cesion',
            name='FHAlta',
        ),
        migrations.RemoveField(
            model_name='cesion',
            name='FHModificacion',
        ),
        migrations.RemoveField(
            model_name='condominio',
            name='DatosAdicionales',
        ),
        migrations.RemoveField(
            model_name='condominio',
            name='FHAlta',
        ),
        migrations.RemoveField(
            model_name='condominio',
            name='FHModificacion',
        ),
        migrations.RemoveField(
            model_name='contrato_arrendamiento',
            name='DatosAdicionales',
        ),
        migrations.RemoveField(
            model_name='contrato_arrendamiento',
            name='FHAlta',
        ),
        migrations.RemoveField(
            model_name='contrato_arrendamiento',
            name='FHModificacion',
        ),
        migrations.RemoveField(
            model_name='emabargo',
            name='DatosAdicionales',
        ),
        migrations.RemoveField(
            model_name='emabargo',
            name='FHAlta',
        ),
        migrations.RemoveField(
            model_name='emabargo',
            name='FHModificacion',
        ),
        migrations.RemoveField(
            model_name='fideicomiso',
            name='DatosAdicionales',
        ),
        migrations.RemoveField(
            model_name='fideicomiso',
            name='FHAlta',
        ),
        migrations.RemoveField(
            model_name='fideicomiso',
            name='FHModificacion',
        ),
        migrations.RemoveField(
            model_name='fraccionamiento',
            name='DatosAdicionales',
        ),
        migrations.RemoveField(
            model_name='fraccionamiento',
            name='FHAlta',
        ),
        migrations.RemoveField(
            model_name='fraccionamiento',
            name='FHModificacion',
        ),
        migrations.RemoveField(
            model_name='fusion',
            name='DatosAdicionales',
        ),
        migrations.RemoveField(
            model_name='fusion',
            name='FHAlta',
        ),
        migrations.RemoveField(
            model_name='fusion',
            name='FHModificacion',
        ),
        migrations.RemoveField(
            model_name='gravamen',
            name='DatosAdicionales',
        ),
        migrations.RemoveField(
            model_name='gravamen',
            name='FHAlta',
        ),
        migrations.RemoveField(
            model_name='gravamen',
            name='FHModificacion',
        ),
        migrations.RemoveField(
            model_name='inmatriculacion_folio_inmobiliario',
            name='DatosAdicionales',
        ),
        migrations.RemoveField(
            model_name='inmatriculacion_folio_inmobiliario',
            name='FHAlta',
        ),
        migrations.RemoveField(
            model_name='inmatriculacion_folio_inmobiliario',
            name='FHModificacion',
        ),
        migrations.RemoveField(
            model_name='partcipante',
            name='DatosAdicionales',
        ),
        migrations.RemoveField(
            model_name='partcipante',
            name='FHAlta',
        ),
        migrations.RemoveField(
            model_name='partcipante',
            name='FHModificacion',
        ),
        migrations.RemoveField(
            model_name='reserva_dominio',
            name='DatosAdicionales',
        ),
        migrations.RemoveField(
            model_name='reserva_dominio',
            name='FHAlta',
        ),
        migrations.RemoveField(
            model_name='reserva_dominio',
            name='FHModificacion',
        ),
        migrations.RemoveField(
            model_name='sentencia',
            name='DatosAdicionales',
        ),
        migrations.RemoveField(
            model_name='sentencia',
            name='FHAlta',
        ),
        migrations.RemoveField(
            model_name='sentencia',
            name='FHModificacion',
        ),
        migrations.RemoveField(
            model_name='subdivision',
            name='DatosAdicionales',
        ),
        migrations.RemoveField(
            model_name='subdivision',
            name='FHAlta',
        ),
        migrations.RemoveField(
            model_name='subdivision',
            name='FHModificacion',
        ),
        migrations.RemoveField(
            model_name='traslado_dominio',
            name='DatosAdicionales',
        ),
        migrations.RemoveField(
            model_name='traslado_dominio',
            name='FHAlta',
        ),
        migrations.RemoveField(
            model_name='traslado_dominio',
            name='FHModificacion',
        ),
        migrations.RemoveField(
            model_name='usufructo',
            name='DatosAdicionales',
        ),
        migrations.RemoveField(
            model_name='usufructo',
            name='FHAlta',
        ),
        migrations.RemoveField(
            model_name='usufructo',
            name='FHModificacion',
        ),
        migrations.AlterField(
            model_name='acto_vario',
            name='FolioActo',
            field=models.OneToOneField(db_column='FOLIOACTO', help_text='Acto al que corresponde', null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.acto_inmobiliario', verbose_name='Acto'),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='Cadena',
            field=models.CharField(db_column='AUTORIZACION', help_text='Cadena de autorización', max_length=300, primary_key=True, serialize=False, unique=True, verbose_name='Cadena de autorización'),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='DatosAdicionales',
            field=models.JSONField(db_column='DATOSADICIONALES', null=True),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='Detalles',
            field=models.JSONField(db_column='DETALLES', help_text='Detalles de la autorización', verbose_name='Detalles'),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 2, 12, 19, 0, 1, 928222, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='FHAutorizacion',
            field=models.DateTimeField(db_column='FHAUTORIZACION', db_default=datetime.datetime(2025, 2, 12, 19, 0, 1, 928198, tzinfo=datetime.timezone.utc), help_text='Fecha y hora del registro de la autorización', verbose_name='Fecha y hora de la autorización'),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='FHModificacion',
            field=models.DateTimeField(db_column='FHMODIF', null=True),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='FirmadoElectronicamente',
            field=models.BooleanField(db_column='FIRMADOELEC', db_default=True, help_text='Firmado electrónicamente si es verdadero', verbose_name='e-firma'),
        ),
        migrations.AlterField(
            model_name='aviso_preventivo',
            name='FolioActo',
            field=models.OneToOneField(db_column='FOLIOACTO', help_text='Acto al que corresponde', null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.acto_inmobiliario', verbose_name='Acto'),
        ),
        migrations.AlterField(
            model_name='cesion',
            name='FolioActo',
            field=models.OneToOneField(db_column='FOLIOACTO', help_text='Acto al que corresponde', null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.acto_inmobiliario', verbose_name='Acto'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='FolioActo',
            field=models.OneToOneField(db_column='FOLIOACTO', help_text='Acto al que corresponde', null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.acto_inmobiliario', verbose_name='Acto'),
        ),
        migrations.AlterField(
            model_name='contrato_arrendamiento',
            name='FolioActo',
            field=models.OneToOneField(db_column='FOLIOACTO', help_text='Acto al que corresponde', null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.acto_inmobiliario', verbose_name='Acto'),
        ),
        migrations.AlterField(
            model_name='emabargo',
            name='FolioActo',
            field=models.OneToOneField(db_column='FOLIOACTO', help_text='Acto al que corresponde', null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.acto_inmobiliario', verbose_name='Acto'),
        ),
        migrations.AlterField(
            model_name='fideicomiso',
            name='FolioActo',
            field=models.OneToOneField(db_column='FOLIOACTO', help_text='Acto al que corresponde', null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.acto_inmobiliario', verbose_name='Acto'),
        ),
        migrations.AlterField(
            model_name='fraccionamiento',
            name='FolioActo',
            field=models.OneToOneField(db_column='FOLIOACTO', help_text='Acto al que corresponde', null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.acto_inmobiliario', verbose_name='Acto'),
        ),
        migrations.AlterField(
            model_name='fusion',
            name='FolioActo',
            field=models.OneToOneField(db_column='FOLIOACTO', help_text='Acto al que corresponde', null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.acto_inmobiliario', verbose_name='Acto'),
        ),
        migrations.AlterField(
            model_name='gravamen',
            name='FolioActo',
            field=models.OneToOneField(db_column='FOLIOACTO', help_text='Acto al que corresponde', null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.acto_inmobiliario', verbose_name='Acto'),
        ),
        migrations.AlterField(
            model_name='inmatriculacion_folio_inmobiliario',
            name='FolioActo',
            field=models.OneToOneField(db_column='FOLIOACTO', help_text='Acto al que corresponde', null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.acto_inmobiliario', verbose_name='Acto'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 2, 12, 19, 0, 1, 929170, tzinfo=datetime.timezone.utc), verbose_name='Fecha y hora del alta'),
        ),
        migrations.AlterField(
            model_name='partcipante',
            name='FolioActo',
            field=models.OneToOneField(db_column='FOLIOACTO', help_text='Acto al que corresponde', null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.acto_inmobiliario', verbose_name='Acto'),
        ),
        migrations.AlterField(
            model_name='reserva_dominio',
            name='FolioActo',
            field=models.OneToOneField(db_column='FOLIOACTO', help_text='Acto al que corresponde', null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.acto_inmobiliario', verbose_name='Acto'),
        ),
        migrations.AlterField(
            model_name='sentencia',
            name='FolioActo',
            field=models.OneToOneField(db_column='FOLIOACTO', help_text='Acto al que corresponde', null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.acto_inmobiliario', verbose_name='Acto'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='FolioActo',
            field=models.OneToOneField(db_column='FOLIOACTO', help_text='Acto al que corresponde', null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.acto_inmobiliario', verbose_name='Acto'),
        ),
        migrations.AlterField(
            model_name='traslado_dominio',
            name='FolioActo',
            field=models.OneToOneField(db_column='FOLIOACTO', help_text='Acto al que corresponde', null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.acto_inmobiliario', verbose_name='Acto'),
        ),
        migrations.AlterField(
            model_name='usufructo',
            name='FolioActo',
            field=models.OneToOneField(db_column='FOLIOACTO', help_text='Acto al que corresponde', null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.acto_inmobiliario', verbose_name='Acto'),
        ),
    ]
