# Generated by Django 5.1.5 on 2025-02-13 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_alter_autorizacion_fhalta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='control_siger',
            fields=[
                ('idEntrada', models.AutoField(db_column='IDENTRADA', primary_key=True, serialize=False, unique=True, verbose_name='Identificador único')),
                ('Variable', models.CharField(db_column='VARIABLE', db_default='VAR', db_index=True, help_text='Variable', max_length=50, unique=True, verbose_name='Variable')),
                ('Valor', models.CharField(db_column='VALOR', db_default='VAL', help_text='Valor', max_length=200, verbose_name='Valor')),
            ],
            options={
                'verbose_name_plural': 'Tabla de control y configuración',
                'ordering': ('Variable', 'Valor'),
            },
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 2, 13, 11, 59, 25, 386777, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='FHAutorizacion',
            field=models.DateTimeField(db_column='FHAUTORIZACION', db_default=datetime.datetime(2025, 2, 13, 11, 59, 25, 386752, tzinfo=datetime.timezone.utc), help_text='Fecha y hora del registro de la autorización', verbose_name='Fecha y hora de la autorización'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 2, 13, 11, 59, 25, 387688, tzinfo=datetime.timezone.utc), verbose_name='Fecha y hora del alta'),
        ),
    ]
