# Generated by Django 5.1.5 on 2025-02-13 17:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_alter_autorizacion_fhalta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='lista_negra_folios_inmobiliarios',
            fields=[
                ('IdEntrada', models.BigAutoField(db_column='IDENTRADA', db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Identificador único')),
                ('FolioReal', models.CharField(db_column='FOLIOREAL', db_index=True, help_text='Folio real en la lista negra', max_length=40, unique=True, verbose_name='Folio real')),
                ('Causa', models.SmallIntegerField(choices=[(0, 'No se puede determinar'), (1, 'Por cancelación'), (2, 'Por error material'), (3, 'Por error inmaterial'), (4, 'Por orden judicial'), (5, 'Por error sistemático')], db_column='CAUSA', db_default=0, help_text='Causa de la incorporación a la lista negra', verbose_name='Causa')),
                ('Observaciones', models.TextField(db_column='OBSERVACIONES', help_text='Observaciones', null=True, verbose_name='Observaciones')),
                ('DatosAdicionales', models.JSONField(db_column='DATOSADICIONALES')),
                ('FHAlta', models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 2, 13, 17, 5, 39, 67738, tzinfo=datetime.timezone.utc), help_text='Fecha y hora de la incorporación', verbose_name='Fecha y hora incorporación')),
                ('FHModificacion', models.DateTimeField(db_column='FHMODIF')),
            ],
            options={
                'verbose_name_plural': 'Lista negra de folios inmobiliarios',
                'ordering': ('FolioReal', 'FHAlta', 'Causa'),
            },
        ),
        migrations.CreateModel(
            name='lista_negra_folios_no_inmobiliarios',
            fields=[
                ('IdEntrada', models.BigAutoField(db_column='IDENTRADA', db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Identificador único')),
                ('FolioReal', models.CharField(db_column='FOLIOREAL', db_index=True, help_text='Folio real en la lista negra', max_length=40, unique=True, verbose_name='Folio real')),
                ('Causa', models.SmallIntegerField(choices=[(0, 'No se puede determinar'), (1, 'Por cancelación'), (2, 'Por error material'), (3, 'Por error inmaterial'), (4, 'Por orden judicial'), (5, 'Por error sistemático')], db_column='CAUSA', db_default=0, help_text='Causa de la incorporación a la lista negra', verbose_name='Causa')),
                ('Observaciones', models.TextField(db_column='OBSERVACIONES', help_text='Observaciones', null=True, verbose_name='Observaciones')),
                ('DatosAdicionales', models.JSONField(db_column='DATOSADICIONALES')),
                ('FHAlta', models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 2, 13, 17, 5, 39, 68019, tzinfo=datetime.timezone.utc), help_text='Fecha y hora de la incorporación', verbose_name='Fecha y hora incorporación')),
                ('FHModificacion', models.DateTimeField(db_column='FHMODIF')),
            ],
            options={
                'verbose_name_plural': 'Lista negra de folios no inmobiliarios',
                'ordering': ('FolioReal', 'FHAlta', 'Causa'),
            },
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 2, 13, 17, 5, 39, 56376, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='FHAutorizacion',
            field=models.DateTimeField(db_column='FHAUTORIZACION', db_default=datetime.datetime(2025, 2, 13, 17, 5, 39, 56351, tzinfo=datetime.timezone.utc), help_text='Fecha y hora del registro de la autorización', verbose_name='Fecha y hora de la autorización'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 2, 13, 17, 5, 39, 57460, tzinfo=datetime.timezone.utc), verbose_name='Fecha y hora del alta'),
        ),
        migrations.CreateModel(
            name='r_acto_no_inm_instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RolInstrumento', models.PositiveSmallIntegerField(choices=[(0, 'Desconocido'), (1, 'Inscripción'), (2, 'Cancelación'), (3, 'Corrección de error material'), (4, 'Orden judicial')], db_column='ROLINSTRUMENTO', db_default=0)),
                ('FolioActo', models.ForeignKey(db_column='FOLIOACTO', on_delete=django.db.models.deletion.CASCADE, to='registro.acto_no_inmobiliario')),
                ('IdInstrumento', models.ForeignKey(db_column='IDINSTRUMENTO', on_delete=django.db.models.deletion.CASCADE, to='registro.instrumento')),
            ],
        ),
    ]
