# Generated by Django 5.1.5 on 2025-03-22 19:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('registro', '0007_lista_negra_folios_inmobiliarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folio_inmobiliario',
            name='ClaveGeoEntidad',
        ),
        migrations.RemoveField(
            model_name='folio_inmobiliario',
            name='ClaveGeoLocalidad',
        ),
        migrations.RemoveField(
            model_name='folio_inmobiliario',
            name='ClaveGeoMunicipio',
        ),
        migrations.RemoveField(
            model_name='folio_inmobiliario',
            name='HashDomicilio',
        ),
        migrations.RemoveField(
            model_name='folio_inmobiliario',
            name='Km',
        ),
        migrations.RemoveField(
            model_name='folio_inmobiliario',
            name='Lote',
        ),
        migrations.RemoveField(
            model_name='folio_inmobiliario',
            name='Manzana',
        ),
        migrations.RemoveField(
            model_name='folio_inmobiliario',
            name='Pais',
        ),
        migrations.AddField(
            model_name='folio_inmobiliario',
            name='TipoNumeracion',
            field=models.SmallIntegerField(choices=[(0, 'Número exterior'), (1, 'Km en carretera o camino'), (2, 'Manzana'), (3, 'Otro')], db_column='TIPONUMERACION', db_default=0, verbose_name='Tipo de numeración exterior'),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 3, 22, 19, 37, 16, 387739, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='FHAutorizacion',
            field=models.DateTimeField(db_column='FHAUTORIZACION', db_default=datetime.datetime(2025, 3, 22, 19, 37, 16, 387715, tzinfo=datetime.timezone.utc), help_text='Fecha y hora del registro de la autorización', verbose_name='Fecha y hora de la autorización'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='AliasAsentamiento',
            field=models.CharField(db_column='ASENTAMIENTO', max_length=50, null=True, verbose_name='Alias asentamiento'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='Ambito',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Urbano'), (1, 'Rural'), (2, 'Suburbano'), (3, 'Rústico')], db_column='AMBITO', default=0, verbose_name='Ámbito (urbano, rural, etc.)'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='ClaveCatastral',
            field=models.CharField(db_column='CVECATASTRAL', max_length=40, null=True, verbose_name='Clave catastral del inmueble'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='ClaveGeoAsentamiento',
            field=models.ForeignKey(db_column='CLAVEASENTAMIENTO', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.c_asentamiento_humano', verbose_name='Asentamiento'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='CuadroConstruccion',
            field=models.JSONField(db_column='CUADROCONSTRUCCION', null=True, verbose_name='Cuatro de construcción (coordenadas de los vértices)'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='DatosAdicionales',
            field=models.JSONField(db_column='DATOSADICIONALES', null=True, verbose_name='Datos adicionales'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='Descripcion',
            field=models.TextField(db_column='DESCRIPCION', null=True, verbose_name='Descripción del inmueble'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='EsCondominio',
            field=models.BooleanField(db_column='ESCONDOMINIO', default=False, verbose_name='Verdadero si es un folio de condominio'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='EsFolioMatriz',
            field=models.BooleanField(db_column='ESFOLIOMATRIZ', default=False, verbose_name='Verdadero si es folio matriz'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 3, 22, 19, 37, 16, 391834, tzinfo=datetime.timezone.utc), verbose_name='Fecha y hora alta del registro'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='FHCancelacion',
            field=models.DateTimeField(db_column='FHCANCELACION', verbose_name='Fecha y hora dela cancelación'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='FHModificacion',
            field=models.DateTimeField(db_column='FHMODIF', null=True, verbose_name='Fecha y hora  de la última modificación'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='FUltimoValor',
            field=models.DateField(db_column='FULTIMOVALOR', null=True, verbose_name='Fecha del último avalúo'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='FolioActoProdCancelacion',
            field=models.CharField(db_column='FOLIOACTOCAN', max_length=40, null=True, verbose_name='Folio cancelado producto del actual'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='FolioCancelado',
            field=models.BooleanField(db_column='FOLIOCANCELADO', default=False, verbose_name='Estatus del folio (verdadero=cancelado)'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='FolioCondominio',
            field=models.CharField(db_column='FOLIOCONDOMINIO', max_length=40, null=True, verbose_name='Folio del condominio al que pertenece'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='FolioMatriz',
            field=models.CharField(db_column='FOLIOMATRIZ', max_length=40, null=True, verbose_name='Folio matriz'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='FolioProdCancelacion',
            field=models.CharField(db_column='FOLIOCAN', max_length=40, null=True, verbose_name='Folio que genera su cancelación'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='FolioReal',
            field=models.CharField(db_column='FOLIO', db_index=True, max_length=40, primary_key=True, serialize=False, verbose_name='Folio real inmobiliario'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='IdUsoInmueble',
            field=models.ForeignKey(db_column='IDUSOINMUEBLE', null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.c_uso_inmueble', verbose_name='Uso del inmueble'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='Latitud',
            field=models.FloatField(db_column='LAT', default=0.0, verbose_name='Latitud (coordenadas geográficas)'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='Logitud',
            field=models.FloatField(db_column='LON', default=0.0, verbose_name='Longitud (coordenadas geográficas)'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='MetodoInmatriculacion',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inmatriculación'), (1, 'Inmatriculación judicial'), (2, 'Pase a folio'), (3, 'Por fusión'), (4, 'Por subdivisión')], db_column='METODOINMAT', db_default=0, verbose_name='Vía de inmatriculación'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='NombreInmueble',
            field=models.CharField(db_column='NOMBREINMUEBLE', db_index=True, max_length=100, null=True, verbose_name='Nombre del inmueble'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='NumeroExterior',
            field=models.CharField(db_column='NUMEXTERIOR', db_index=True, max_length=10, null=True, verbose_name='Número exterior / km / manzana'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='NumeroInterior',
            field=models.CharField(db_column='NUMINTERIOR', max_length=10, null=True, verbose_name='Número interior / departamento / lote'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='Observaciones',
            field=models.TextField(db_column='OBSERVACIONES', null=True, verbose_name='Obervaciones al instrumento y/o inmueble'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='SuperficieConstruccion',
            field=models.FloatField(db_column='SUPERFICIECONSTRUCCION', default=0.0, null=True, verbose_name='Superficie total de los elementos constructivos'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='SuperficieIndiviso',
            field=models.FloatField(db_column='SUPERFICIEINDIVISO', default=0.0, verbose_name='Superficie de indiviso'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='SuperficieSuelo',
            field=models.FloatField(db_column='SUPERFICIESUELO', default=0.0, verbose_name='Superficie del suelo'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='TipoVialidad',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Calle'), (1, 'Avenida'), (2, 'Periférico'), (3, 'Cerrada'), (4, 'Calzada'), (5, 'Eje vial'), (6, 'Privada'), (7, 'Circuito'), (8, 'Viaducto'), (9, 'Pasaje'), (10, 'Peatonal'), (11, 'Continuación'), (12, 'Callejón'), (13, 'Corredor'), (14, 'Prolongación'), (15, 'Andador'), (16, 'Carretera'), (17, 'Boulevard'), (18, 'Ampliación'), (19, 'Circunvalación'), (20, 'Glorieta'), (21, 'Carretera'), (22, 'Retorno'), (23, 'Enlace'), (24, 'Vereda'), (25, 'Diagonal'), (26, 'Retorno U'), (27, 'Rampa de frenado'), (28, 'Otro')], db_column='TIPOVIALIDAD', db_default=0, verbose_name='Tipo de vialidad'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='UltimoValorInmueble',
            field=models.FloatField(db_column='ULTIMOVALOR', db_default=0.0, verbose_name='Valor del inmueble de la última avalúo'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='Vialidad',
            field=models.CharField(db_column='VIALIDAD', db_default='', db_index=True, max_length=100, verbose_name='Vialidad'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 3, 22, 19, 37, 16, 388692, tzinfo=datetime.timezone.utc), verbose_name='Fecha y hora del alta'),
        ),
        migrations.AlterField(
            model_name='lista_negra_folios_inmobiliarios',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 3, 22, 19, 37, 16, 399232, tzinfo=datetime.timezone.utc), help_text='Fecha y hora de la incorporación', verbose_name='Fecha y hora incorporación'),
        ),
        migrations.AlterField(
            model_name='lista_negra_folios_no_inmobiliarios',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 3, 22, 19, 37, 16, 399384, tzinfo=datetime.timezone.utc), help_text='Fecha y hora de la incorporación', verbose_name='Fecha y hora incorporación'),
        ),
    ]
