# Generated by Django 5.1.5 on 2025-05-04 02:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_remove_folio_inmobiliario_clavegeoentidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='c_tipo_acto_inmobiliario',
            fields=[
                ('IdTipoActo', models.SmallAutoField(db_column='IDTIPOACTO', db_comment='Identificador único', db_index=True, primary_key=True, serialize=False, unique=True)),
                ('NombreActo', models.CharField(db_column='NOMBRE', db_comment='Nombre del acto', max_length=50, unique=True)),
                ('Tabla', models.CharField(db_column='TABLA', db_comment='Tabla', db_index=True, max_length=50)),
                ('Llave', models.CharField(db_column='LLAVEPRIMARIA', db_comment='Llave primaria', max_length=50)),
                ('FHAlta', models.DateTimeField(db_column='FHALTA', db_comment='Fecha y hora de alta')),
                ('FHModificacion', models.DateTimeField(db_column='FHMODIF', db_comment='Fecha y hora de modificación')),
            ],
            options={
                'verbose_name_plural': 'Catálogo tipos de actos',
                'ordering': ('NombreActo', 'IdTipoActo', 'Tabla', 'Llave'),
            },
        ),
        migrations.AlterModelOptions(
            name='folio_inmobiliario',
            options={'ordering': ('FolioReal',), 'verbose_name_plural': 'Entidad de folios inmobiliarios (INMUEBLES)'},
        ),
        migrations.AlterField(
            model_name='acto_inmobiliario',
            name='ActoHistorico',
            field=models.BooleanField(db_column='ACTOHISTORICO', db_comment='Acto histórico', db_default=False),
        ),
        migrations.AlterField(
            model_name='acto_inmobiliario',
            name='DatosAdicionales',
            field=models.JSONField(db_column='DATOSADICIONALES', db_comment='Datos adicionales'),
        ),
        migrations.AlterField(
            model_name='acto_inmobiliario',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_comment='Fecha y hora del alta del registro'),
        ),
        migrations.AlterField(
            model_name='acto_inmobiliario',
            name='FHCancelacion',
            field=models.DateTimeField(db_column='FHCANCELACION', db_comment='Fecha y hora de la cancelación'),
        ),
        migrations.AlterField(
            model_name='acto_inmobiliario',
            name='FHInscripcion',
            field=models.DateTimeField(db_column='FHINSCRIPCION', db_comment='Fecha y hora de la inscripción'),
        ),
        migrations.AlterField(
            model_name='acto_inmobiliario',
            name='FHModificacion',
            field=models.DateTimeField(db_column='FHMODIF', db_comment='Fecha y hora de la última modificación'),
        ),
        migrations.AlterField(
            model_name='acto_inmobiliario',
            name='FolioActo',
            field=models.CharField(db_column='FOLIOACTO', db_comment='Folio del acto', db_index=True, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='acto_inmobiliario',
            name='Vigente',
            field=models.BooleanField(db_column='VIGENTE', db_comment='Vigente', db_default=True),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 5, 4, 2, 22, 31, 217350, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='FHAutorizacion',
            field=models.DateTimeField(db_column='FHAUTORIZACION', db_default=datetime.datetime(2025, 5, 4, 2, 22, 31, 217326, tzinfo=datetime.timezone.utc), help_text='Fecha y hora del registro de la autorización', verbose_name='Fecha y hora de la autorización'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 5, 4, 2, 22, 31, 221525, tzinfo=datetime.timezone.utc), verbose_name='Fecha y hora alta del registro'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='TipoNumeracion',
            field=models.SmallIntegerField(choices=[(0, 'Número exterior - interior'), (1, 'Km'), (2, 'Manzana - lote'), (3, 'Edificio - departamento'), (4, 'Privada - casa'), (5, 'Unidad - edificio - departamento')], db_column='TIPONUMERACION', db_default=0, verbose_name='Tipo de numeración exterior'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 5, 4, 2, 22, 31, 218306, tzinfo=datetime.timezone.utc), verbose_name='Fecha y hora del alta'),
        ),
        migrations.AlterField(
            model_name='lista_negra_folios_inmobiliarios',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 5, 4, 2, 22, 31, 229112, tzinfo=datetime.timezone.utc), help_text='Fecha y hora de la incorporación', verbose_name='Fecha y hora incorporación'),
        ),
        migrations.AlterField(
            model_name='lista_negra_folios_no_inmobiliarios',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 5, 4, 2, 22, 31, 229396, tzinfo=datetime.timezone.utc), help_text='Fecha y hora de la incorporación', verbose_name='Fecha y hora incorporación'),
        ),
        migrations.AddField(
            model_name='acto_inmobiliario',
            name='TipoActoInmobiliario',
            field=models.ForeignKey(db_column='TIPOACTO', db_comment='Tipo de acto inmobiliario', null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.c_tipo_acto_inmobiliario'),
        ),
    ]
