# Generated by Django 5.1.5 on 2025-05-04 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_c_tipo_acto_inmobiliario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_tipo_acto_inmobiliario',
            name='TipoCampoLlave',
            field=models.SmallIntegerField(choices=[(0, 'Sin definir'), (1, 'Int'), (2, 'Text'), (3, 'Date'), (4, 'Date-time'), (5, 'URL'), (6, 'Email'), (7, 'Currency'), (8, 'Geometry'), (9, 'Name-field'), (10, 'Password-field')], db_column='TIPOCAMPO', db_comment='Tipo de campo', db_default=0),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 5, 4, 2, 29, 17, 679001, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='FHAutorizacion',
            field=models.DateTimeField(db_column='FHAUTORIZACION', db_default=datetime.datetime(2025, 5, 4, 2, 29, 17, 678975, tzinfo=datetime.timezone.utc), help_text='Fecha y hora del registro de la autorización', verbose_name='Fecha y hora de la autorización'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 5, 4, 2, 29, 17, 684436, tzinfo=datetime.timezone.utc), verbose_name='Fecha y hora alta del registro'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 5, 4, 2, 29, 17, 680269, tzinfo=datetime.timezone.utc), verbose_name='Fecha y hora del alta'),
        ),
        migrations.AlterField(
            model_name='lista_negra_folios_inmobiliarios',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 5, 4, 2, 29, 17, 692929, tzinfo=datetime.timezone.utc), help_text='Fecha y hora de la incorporación', verbose_name='Fecha y hora incorporación'),
        ),
        migrations.AlterField(
            model_name='lista_negra_folios_no_inmobiliarios',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 5, 4, 2, 29, 17, 693093, tzinfo=datetime.timezone.utc), help_text='Fecha y hora de la incorporación', verbose_name='Fecha y hora incorporación'),
        ),
    ]
