# Generated by Django 5.1.5 on 2025-05-04 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_c_tipo_acto_inmobiliario_tipocampollave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_tipo_acto_inmobiliario',
            name='Vigente',
            field=models.BooleanField(db_column='Vigencia', db_comment='Vigencia', db_default=False),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 5, 4, 2, 31, 10, 637285, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='FHAutorizacion',
            field=models.DateTimeField(db_column='FHAUTORIZACION', db_default=datetime.datetime(2025, 5, 4, 2, 31, 10, 637256, tzinfo=datetime.timezone.utc), help_text='Fecha y hora del registro de la autorización', verbose_name='Fecha y hora de la autorización'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 5, 4, 2, 31, 10, 642501, tzinfo=datetime.timezone.utc), verbose_name='Fecha y hora alta del registro'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 5, 4, 2, 31, 10, 638651, tzinfo=datetime.timezone.utc), verbose_name='Fecha y hora del alta'),
        ),
        migrations.AlterField(
            model_name='lista_negra_folios_inmobiliarios',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 5, 4, 2, 31, 10, 651298, tzinfo=datetime.timezone.utc), help_text='Fecha y hora de la incorporación', verbose_name='Fecha y hora incorporación'),
        ),
        migrations.AlterField(
            model_name='lista_negra_folios_no_inmobiliarios',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 5, 4, 2, 31, 10, 651464, tzinfo=datetime.timezone.utc), help_text='Fecha y hora de la incorporación', verbose_name='Fecha y hora incorporación'),
        ),
    ]
