# Generated by Django 5.1.5 on 2025-05-04 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0012_c_tipo_acto_no_inmobiliario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='c_clase_acto_juridico',
            fields=[
                ('IdClaseActo', models.SmallAutoField(db_column='IDCLASEACTO', db_comment='Identificador de la clase de acto', db_index=True, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='NOMBRE', db_comment='Nombre de la clase de acto', db_index=True, max_length=50)),
                ('Descripcion', models.TextField(db_column='DESCRIPCION', db_comment='Descripción', null=True)),
                ('Limitativo', models.BooleanField(db_column='LIMITATIVA', db_comment='Clase de actos limitativos al dominio', db_default=False)),
                ('Modificatoria', models.BooleanField(db_column='MODIFICATORIA', db_comment='Clase de actos modifican el carátula/inmueble', db_default=False)),
                ('Traslativo', models.BooleanField(db_column='TRASLATIVO', db_comment='Clase de acto modifica dominio', db_default=False)),
                ('Judicial', models.BooleanField(db_column='JUDICIAL', db_comment='Clase de acto judicial', db_default=False)),
                ('Administrativo', models.BooleanField(db_column='ADMINISTRATIVO', db_comment='Clase de acto administrativo', db_default=False)),
                ('Aviso', models.BooleanField(db_column='AVISO', db_comment='Clase de acto de aviso', db_default=False)),
                ('Vigente', models.BooleanField(db_column='Vigencia', db_comment='Vigencia', db_default=False)),
                ('FHAlta', models.DateTimeField(db_column='FHALTA', db_comment='Fecha y hora de alta')),
                ('FHModificacion', models.DateTimeField(db_column='FHMODIF', db_comment='Fecha y hora de modificación')),
            ],
            options={
                'verbose_name_plural': 'Catálogo de clases de actos',
                'ordering': ('Nombre', 'IdClaseActo'),
            },
        ),
        migrations.AlterModelOptions(
            name='c_tipo_acto_inmobiliario',
            options={'ordering': ('Nombre', 'IdTipoActo', 'Tabla', 'Llave'), 'verbose_name_plural': 'Catálogo tipos de actos'},
        ),
        migrations.AlterModelOptions(
            name='c_tipo_acto_no_inmobiliario',
            options={'ordering': ('Nombre', 'IdTipoActo', 'Tabla', 'Llave'), 'verbose_name_plural': 'Catálogo tipos de actos'},
        ),
        migrations.RenameField(
            model_name='c_tipo_acto_inmobiliario',
            old_name='NombreActo',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='c_tipo_acto_no_inmobiliario',
            old_name='NombreActo',
            new_name='Nombre',
        ),
        migrations.AddField(
            model_name='c_tipo_acto_inmobiliario',
            name='Descripcion',
            field=models.TextField(db_column='DESCRIPCION', db_comment='Descripción', null=True),
        ),
        migrations.AddField(
            model_name='c_tipo_acto_no_inmobiliario',
            name='Descripcion',
            field=models.TextField(db_column='DESCRIPCION', db_comment='Descripción', null=True),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 5, 4, 2, 55, 43, 299665, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='FHAutorizacion',
            field=models.DateTimeField(db_column='FHAUTORIZACION', db_default=datetime.datetime(2025, 5, 4, 2, 55, 43, 299640, tzinfo=datetime.timezone.utc), help_text='Fecha y hora del registro de la autorización', verbose_name='Fecha y hora de la autorización'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 5, 4, 2, 55, 43, 303889, tzinfo=datetime.timezone.utc), verbose_name='Fecha y hora alta del registro'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 5, 4, 2, 55, 43, 300576, tzinfo=datetime.timezone.utc), verbose_name='Fecha y hora del alta'),
        ),
        migrations.AlterField(
            model_name='lista_negra_folios_inmobiliarios',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 5, 4, 2, 55, 43, 311922, tzinfo=datetime.timezone.utc), help_text='Fecha y hora de la incorporación', verbose_name='Fecha y hora incorporación'),
        ),
        migrations.AlterField(
            model_name='lista_negra_folios_no_inmobiliarios',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 5, 4, 2, 55, 43, 312073, tzinfo=datetime.timezone.utc), help_text='Fecha y hora de la incorporación', verbose_name='Fecha y hora incorporación'),
        ),
    ]
