# Generated by Django 5.1.5 on 2025-05-04 03:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0013_c_clase_acto_juridico_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='c_clase_acto_juridico',
            new_name='c_clase_acto',
        ),
        migrations.AddField(
            model_name='c_tipo_acto_inmobiliario',
            name='ClaseActo',
            field=models.ForeignKey(db_column='CLASEACTO', db_comment='Clase de acto', null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.c_clase_acto'),
        ),
        migrations.AddField(
            model_name='c_tipo_acto_no_inmobiliario',
            name='ClaseActo',
            field=models.ForeignKey(db_column='CLASEACTO', db_comment='Clase de acto', null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.c_clase_acto'),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 5, 4, 3, 0, 57, 488878, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='FHAutorizacion',
            field=models.DateTimeField(db_column='FHAUTORIZACION', db_default=datetime.datetime(2025, 5, 4, 3, 0, 57, 488851, tzinfo=datetime.timezone.utc), help_text='Fecha y hora del registro de la autorización', verbose_name='Fecha y hora de la autorización'),
        ),
        migrations.AlterField(
            model_name='folio_inmobiliario',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 5, 4, 3, 0, 57, 493520, tzinfo=datetime.timezone.utc), verbose_name='Fecha y hora alta del registro'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', default=datetime.datetime(2025, 5, 4, 3, 0, 57, 489901, tzinfo=datetime.timezone.utc), verbose_name='Fecha y hora del alta'),
        ),
        migrations.AlterField(
            model_name='lista_negra_folios_inmobiliarios',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 5, 4, 3, 0, 57, 503619, tzinfo=datetime.timezone.utc), help_text='Fecha y hora de la incorporación', verbose_name='Fecha y hora incorporación'),
        ),
        migrations.AlterField(
            model_name='lista_negra_folios_no_inmobiliarios',
            name='FHAlta',
            field=models.DateTimeField(db_column='FHALTA', db_default=datetime.datetime(2025, 5, 4, 3, 0, 57, 503825, tzinfo=datetime.timezone.utc), help_text='Fecha y hora de la incorporación', verbose_name='Fecha y hora incorporación'),
        ),
    ]
